heat_template_version: 2016-10-14

description: >
  Template for deploying Ardana in a multinode setup

parameters:
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: engcloud-cloud-ci
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: cleanvm-jeos-SLE12SP3
  instance_type_controller:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used for the controller
    default: m1.xxlarge
  instance_type_compute:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used for compute nodes
    default: m1.large

resources:
  # networks
  network_mgmt:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False
  network_ardana:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False
  network_external:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False

  # subnet
  subnet_mgmt:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_mgmt }
      cidr: "192.168.245.0/24"
      allocation_pools:
          - start: "192.168.245.2"
            end: "192.168.245.100"
      ip_version: 4
      gateway_ip: 192.168.245.1
  subnet_ardana:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_ardana }
      cidr: "192.168.110.0/24"
      allocation_pools:
          - start: "192.168.110.2"
            end: "192.168.110.100"
      ip_version: 4
      gateway_ip: null
  subnet_external:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_external }
      allocation_pools:
          - start: "172.31.0.2"
            end: "172.31.255.154"
      cidr: "172.31.0.0/16"
      enable_dhcp: False
      gateway_ip: 172.31.0.1

  # router
  router_mgmt:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: floating

  router_mgmt_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router_mgmt }
      subnet_id: { get_resource: subnet_mgmt }

  router_external_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router_mgmt }
      subnet_id: { get_resource: subnet_external }

  # floating IPs
  deployer-controller-floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: floating

  # instances
  deployer-controller:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type_controller }
      networks:
        - network: { get_resource: network_mgmt }
        - network: { get_resource: network_ardana }
        - network: { get_resource: network_external }

  compute1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type_compute }
      networks:
        - network: { get_resource: network_mgmt }
        - network: { get_resource: network_ardana }
        - network: { get_resource: network_external }

  compute2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image_id }
      flavor: { get_param: instance_type_compute }
      networks:
        - network: { get_resource: network_mgmt }
        - network: { get_resource: network_ardana }
        - network: { get_resource: network_external }

  # disks
  controller_vdb:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vdc:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vdd:
    type: OS::Cinder::Volume
    properties:
      size: 30
  controller_vde:
    type: OS::Cinder::Volume
    properties:
      size: 30

  controller_vol_att_vdb:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: deployer-controller }
      volume_id: { get_resource: controller_vdb }
      mountpoint: /dev/vdb

  controller_vol_att_vdc:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: deployer-controller }
      volume_id: { get_resource: controller_vdc }
      mountpoint: /dev/vdc
  controller_vol_att_vdd:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: deployer-controller }
      volume_id: { get_resource: controller_vdd }
      mountpoint: /dev/vdd
  controller_vol_att_vde:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: deployer-controller }
      volume_id: { get_resource: controller_vde }
      mountpoint: /dev/vde

  deployer-controller-floating-assignment:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: deployer-controller-floatingip }
      port_id: {get_attr: [deployer-controller, addresses, { get_resource: network_mgmt }, 0, port]}

outputs:
  # deployer-controller
  deployer-ip-floating:
    description: Floating IP address of the deployer-controller node
    value: { get_attr: [deployer-controller-floatingip, floating_ip_address] }

  deployer-net-ardana-ip:
    description: IP address of the deployer-controller in the ardana network
    value: { get_attr: [deployer-controller, networks, { get_resource: network_ardana }, 0]}

  deployer-net-mgmt-ip:
    description: IP address of the deployer-controller in the mgmt network
    value: { get_attr: [deployer-controller, networks, { get_resource: network_mgmt }, 0]}

  # compute1
  compute1-net-ardana-ip:
    description: IP address of the compute1 node in the ardana network
    value: { get_attr: [compute1, networks, { get_resource: network_ardana }, 0]}

  compute1-net-mgmt-ip:
    description: IP address of the compute1 node in the mgmt network
    value: { get_attr: [compute1, networks, { get_resource: network_mgmt }, 0]}

  # compute2
  compute2-net-ardana-ip:
    description: IP address of the compute2 node in the ardana network
    value: { get_attr: [compute2, networks, { get_resource: network_ardana }, 0]}

  compute2-net-mgmt-ip:
    description: IP address of the compute2 node in the mgmt network
    value: { get_attr: [compute2, networks, { get_resource: network_mgmt }, 0]}

  # network info
  network-mgmt-id:
    description: Neutron Network ID of management network
    value: { get_resource: network_mgmt }
